// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using OVR;


public class DisplayText : MonoBehaviour
{
	public string text;
	public bool display = false;
	void OnTriggerEnter(Collider iCollide) {
		if(iCollide.transform.name == "Player") {
			display = true;
		}
	}

	void OnGUI()
	{
		if (display == true) 
		{
			Application.LoadLevel("Ending"); 
			
		}
	}
}


